### ISSUE TITLE
Power Bank External Battery Pack for Charging Devices? 🔋📱

### ISSUE THREAD

**Issue by nelsonic** [edwardcodes/Around-the-World#10]
# _Why_?

When travelling, we are _often_ in places/situations where our digital devices run _low_ on power ...
@iteles and I _always_ carry an External Battery Pack 🔋
because sadly, iPhone is not _known_ for their battery capacity/life 📱 🙄 
so we end up re-charging our phone(s) on-the-go to avoid running out.

> _**Note**: Inês would often carry a battery pack in London 
when she had a long day of meetings outside the office ... 
they are useful for "day-to-day" not just travelling._

I would _highly_ recommend you do your own "requirement gathering": (_share links thoughts below!_)
+ [ ] **how many devices** are you going to take which have a battery that lasts _less_ than a day?
+ [ ] is _weight_ (_saving_) more important than having extra power? e.g: are you spending more time _walking_ (_carrying the pack_) than you are "at rest"? 
  + I don't do much "hiking" so I opted for a [20,000mAh Aukey]() pack which is _heavy_! 
  but if I were climbing Mount Kilimanjaro / Fuji / The Matterhorn / Half Dome / Kala Patthar / _etc_...  I would _definitely_ take a ***lighter*** pack _preferably_ with integrated _Solar_ Panel (_see below_)!
+ [ ] Any extra features like integrated cable, flashlight or impact protection...?

There are **_literally_ hundreds** of available products, 
so you should do some research/reading and draw your own conclusions.
All I will say is: don't leave home without one!

## _One_ USB Port, Cylinder Design (Compact) `5000mAh`

This is the most basic design available.

https://www.amazon.co.uk/Poweradd-Portable-Technology-Lightning-Included-Black/dp/B00MWU1GGI
![image](https://user-images.githubusercontent.com/194400/46002288-99f66a00-c0a5-11e8-9897-494614b03b56.png)

Reviews are generally good, it has "over charge" protection and auto detection.
It will charge your iPhone 6S _twice_ and is only **118g**.

This is very much the "baseline" you should be considering. 
Anything smaller than `5000mAh`

## _One_ USB Port _Compact_ "Chocolate Bar" Design `6700mAh`

RAVPower is one of the most popular brands that make external battery packs. 
(_they have been around for several years and the reviews on Amazon are **consistently good**_!) 

https://www.amazon.co.uk/Portable-Charger-RAVPower-External-Technology-6700mAh-Black/dp/B01LY4SRQ3
![image](https://user-images.githubusercontent.com/194400/45998648-63b3ed00-c09b-11e8-9a1f-414807336e4b.png)

The _advantage of the RAVPower is that it uses "standard" (LG Chem) 3350 cells
which are known to be _highly_ reliable and long-lasting without risk of overheating (_catching fire!_)
at **127g** this is a good option because it will charge your iPhone 3 times and/or other devices you are carrying e.g a Digital Camera >> https://github.com/edwardcodes/Around-the-World/issues/9

## _Two_ USB Ports + USB C, Status Light & _Slim_ Design `6000mAh`

https://www.amazon.co.uk/OKZU-slimline-Lightweight-Portable-External-Gray-Black/dp/B07C215PK7

![image](https://user-images.githubusercontent.com/194400/45999740-78de4b00-c09e-11e8-8911-e4c8d64bd793.png)

## 4 USB Ports _Super Bright Flashlight_ `10000mAh` 🔦 

Consider the scenario where you are walking around Rome and you see someone who looks "_stressed_" because they are "_lost_" and their phone is about to run out of battery,
so they cannot open Maps to lookup where they are or where they are going ... 😖 
(_this is not an "**imaginary**", it's **very real** I see kids running out of power **often**!_)
You, being a "good samaritan",  walk up to them and offer to let them charge their phone on your power bank for a few minutes (until they have "enough juice" to get home safely_).
During the charging time, you strike up a conversation and discover something interesting about ...
(_it does not matter for this thought exercise what you talk about, just that it's **interesting**_!)
The person is _eternally_ grateful to you because you "saved their day" 
and they are _likely_ to buy a battery pack themselves when they get back "home" 
and will "pass it on" next time they see/meet someone who is running low.

https://www.amazon.co.uk/Portable-Charger-10000mAh-Flashlight-Samsung/dp/B07CLJCTMK
![image](https://user-images.githubusercontent.com/194400/46001147-80075800-c0a2-11e8-991a-fa68415feade.png)

The "_Super Bright_" Flashlight is a _great_ feature to have when travelling. 🥇 
Yes, iPhone has an LED flashlight, but it's only "enough" to find your way in a dark room. 📱 🔦 
Having a "_Super Bright_" means you can illuminate a 
And if it's "free" (_integrated into a device you are already carrying_) that's a major bonus.

I personally carry one of these "bike" lights on the outside (top handle) of my backpack:
https://www.amazon.co.uk/Ascher-Rechargeable-LED-Bike-Lights/dp/B01EJ6LKPY
![bike light](https://user-images.githubusercontent.com/194400/46001857-57805d80-c0a4-11e8-95d8-19886dd46af7.png)
it has been _very useful_ several times when I'm walking in the _pitch_ dark in a strange place
(_when there are no street lights and we are walking on cobbled/grass/gravel road_)
The _other_ use for a _Bright_ light is if you are ever walking along the side of a road
and want to be visible to traffic; being seen is a matter of life-and-death!

> You're welcome to take one of our rechargeable Bike Lights to attach to your bag
if you decide to get the smaller battery pack without the light. 
They are good for evening walking because they have a flashing mode which helps drivers see you.

## Solar Panel? ☀️ `10000mAh` 

What if you are hiking up a mountain or _camping_ somewhere **_without_ electricity** for a few days?

https://www.amazon.co.uk/ADDTOP-10000mAh-Separable-Portable-Bluetooth/dp/B075JDCKRW
![image](https://user-images.githubusercontent.com/194400/45999475-aa0a4b80-c09d-11e8-8017-3fd0b886f314.png)

This scenario is _unlikely_ unless you are considering going to a _remote_ village in Nepal/Cambodia or South America / Africa in the near future ... 💭 🌍 
I feel that one of the _other_ options is more _relevant_ to you for your upcoming adventure,
but since the name of repository is "Around-the-World" i.e. you _aspire_ to go "all the way" (around)!
this _could_ be something you could _consider_ in the _future_ after your Europe Trip. 

## Personal _Experience_

I have this one: https://www.amazon.co.uk/dp/B01LXYK955
![image](https://user-images.githubusercontent.com/194400/46000630-06bb3580-c0a1-11e8-8001-6e19d524e597.png)
It's **_super_ heavy** (**445g**) but it **lasts for _ever_** and can charge two devices simultaneously and _fast_. 
I would **_not_ recommend** getting a pack _greater_ than **`10,000mAh`** because it's "***overkill***". 
Your iPhone 6s has a `1715 mAh` battery. The RAVPower **`6700mAh`** will charge it **3 times**!
![image](https://user-images.githubusercontent.com/194400/46000786-75988e80-c0a1-11e8-9046-e769a8d093b1.png)
We _both_ know that the "_official_" talk/music/stand-by times Apple states are _fictional_,
after a year of using the phone the battery life is a _joke_, 😂 😞 
that is why I'm recommending you get an _external_ pack. 

_Please_ add links for your _own_ research and/or share your thoughts on your _own_ requirements. 😉

**Comment by edwardcodes** [comment]
I actually have a small one “but” I will get one a little bit more powerful! 
https://www.fnac.pt/Power-Bank-Eurotech-5200mAh-Preto-Acessorio-Informatica-e-Tel-Carregador-Telemovel/a982585

**Comment by edwardcodes** [comment]
The one with super bright flashlight is incredibly useful though 🤔
