### ISSUE TITLE
Hamburg Container Hotel: 11 - 13 October

### ISSUE THREAD

**Issue by nelsonic** [edwardcodes/Around-the-World#11]
Hi @edwardcodes 

In October @iteles & I are doing a "research trip" to Hamburg to visit this (Shipping) Container Hotel.

> Our **Long Term _Plan_** in https://github.com/dwyl/phase-two 
is to use Shipping Containers to build "***Open Source Affordable Modular Housing***"
Which is _why_ we are using [Maslow CNC](https://github.com/nelsonic/nelsonic.github.io/issues/332) to create all our own _furniture_ ("_from scratch_") 
including kitchen(s), desks, beds, sofas for [https://github.com/dwyl/**home**](https://github.com/dwyl/home)

Hamburg is a _great_ "Port" city with a _few_ things to see:
https://www.tripadvisor.com/Attractions-g187331-Activities-Hamburg.html
I don't think you would need to spend more than a ~~_day_~~ few hours there before moving on ... 
but if you _wanted_ to spend the night so you can catch up on your rest, you could!

But if you are _interested_ in meeting up with us in Hamburg 
and seeing the Container Hotel for a day, 
we would pay for your stay (_somewhere "nice"_) 
and it would be a good "checkpoint" in your InterRail adventure.  

These are our _flight_ details:
![image](https://user-images.githubusercontent.com/194400/46067550-01c4b780-c16f-11e8-9a06-916d115c40e7.png)

If you are _interested_ in joining us, let us know if it "fits" with your "Cities" Plan https://github.com/edwardcodes/Around-the-World/issues/3#issuecomment-424541238

https://www.25hours-hotels.com/en/hotels/hamburg/hafencity
![image](https://user-images.githubusercontent.com/194400/46068149-6b919100-c170-11e8-83ea-ea104a7df32f.png)

![image](https://user-images.githubusercontent.com/194400/46068241-aabfe200-c170-11e8-81bf-5ad6247f9afa.png)

![image](https://user-images.githubusercontent.com/194400/46068053-31c08a80-c170-11e8-87fa-fe79961b6292.png)

![image](https://user-images.githubusercontent.com/194400/46068065-37b66b80-c170-11e8-9ff8-c72ca0b6d078.png)

It's ***100% Optional*** and we don't want to "distract" from your journey/adventure.
But if you are _interested_ in joining us to see the Hotel and go for a meal, please let us know!
(_that way we can subtly be in your "montage" video of your trip all wearing @dwyl T-Shirts..._ 😉)

**Comment by edwardcodes** [comment]
@nelsonic I will be there!!

**Comment by iteles** [comment]
@edwardcodes We'll confirm dates and an address with you asap, the hotel is actually in Warnemünde 😊

**Comment by nelsonic** [comment]
@edwardcodes sadly, due to delays in leaving LX, we are unlikely to see you in Germany this weekend. 😞 

Closing this issue.
