### ISSUE TITLE
Nordics? (The Happiest Place in the World!) 😍 

### ISSUE THREAD

**Issue by nelsonic** [edwardcodes/Around-the-World#12]
@edwardcodes something "_missing_" from your "Cool Cities" List https://github.com/edwardcodes/Around-the-World/issues/3#issuecomment-424541238
which I feel you should "_reconsider_" is the "***Nordics***": https://en.wikipedia.org/wiki/Nordic_countries

According to the World Happiness Report 2018 http://worldhappiness.report/ed/2018/
The Nordic countries are _all_ in the "Top 10" happiest places in the world ...
https://s3.amazonaws.com/happiness-report/2018/WHR_web.pdf
![image](https://user-images.githubusercontent.com/194400/46078550-6c382080-c18c-11e8-94bf-b102f70c8846.png)

# Have you ever been _curious_ ***Why***...?

This is a good summary of the "_The 10 **Happiest Countries** In The World In 2018_"
https://www.forbes.com/sites/duncanmadden/2018/03/27/ranked-the-10-happiest-countries-in-the-world-in-2018

## 9. Stockholm (Sweden)

I've been to Stockholm for work a couple of times and can safely say 
that I would _move_ (_live_) there in a _heartbeat_. 

Our friend Roy _lives_ on lake just outside Stockholm and this is his view:
![roy-sweeden-log-cabin](https://user-images.githubusercontent.com/194400/46078021-d059e500-c18a-11e8-83dc-08ead346ebcf.jpg)

## 4. Iceland 

You can "_ignore_" Iceland for the purposes of an InterRail #2 journey ... 🚂 🚫 😞 

![iceland-europe-map](https://user-images.githubusercontent.com/194400/46074999-15791980-c181-11e8-92b1-ba918a911d9a.jpg)

But _definitely_ keep it on your "Digital Nomad List"
for when you are earning _cash_ for your creative output and can afford to be a "_full-time traveller_"!
Iceland is _incredible_ and _definitely_ on @iteles and my list for _after_ 
see: https://www.tripadvisor.com/Attractions-g189952-Activities-Iceland.html
Given how _expensive_ it is to travel to/in Iceland, we should _each_ budget €1k for it ... 💸 

## 3. Copenhagen (Denmark)

Of all the _nordic_ countries, Denmark is the most "_realistic_" to visit 
on an European InterRail #2 trip purely for _geographic_ reasons ...

![image](https://user-images.githubusercontent.com/194400/46078327-b79dff00-c18b-11e8-8cbf-31f8b77f3883.png)

+ https://www.lonelyplanet.com/denmark/copenhagen
+ https://www.urbanadventures.com/Copenhagen-tour-hygge-happiness

## 2. Oslo (Norway)

![image](https://user-images.githubusercontent.com/194400/46078698-cc2ec700-c18c-11e8-8092-c258dc28b08c.png)

Oslo/Norway is a _great_ place to visit, but it's _even_ further than Stockholm, 
so unless you get the **15-day InterRail Pass** https://github.com/edwardcodes/Around-the-World/issues/2#issuecomment-424684198 
and use the "_night train_" from Stockholm to Oslo
e.g: http://www.raileurope-world.com/train/swedish-night-trains
![image](https://user-images.githubusercontent.com/194400/46076357-36436e00-c185-11e8-973c-bb8e5902ae0d.png)
(_Which would be _smart_ because then you would not have to pay for a Hostel ..._ 😉)

## 1. Helsinki (Finland)

![image](https://user-images.githubusercontent.com/194400/46071844-db0b7e80-c178-11e8-8d22-4ad28e0f3aaa.png)

Finland is a _truly_ awesome_ country.
+ https://en.wikipedia.org/wiki/Education_in_Finland
+ https://www.theguardian.com/cities/2018/may/15/why-finlands-cities-are-havens-for-library-lovers-oodi-helsinki

If you were to adopt the "**`30 Countries` in `30 Days`**" ***Goal*** https://github.com/edwardcodes/Around-the-World/issues/2#issuecomment-424684198
you would be _able_ to see all of the _contiguous_ Nordic Countries! 😮

**Comment by edwardcodes** [comment]
Definitely! I don’t know what I was thinking but they’re in the list!  🇳🇴 🇸🇪 🇩🇰
