### ISSUE TITLE
Packing Cubes

### ISSUE THREAD

**Issue by nelsonic** [edwardcodes/Around-the-World#5]
Most Travelling Guides and "Travel Vloggers" recommend Packing Cubes!
e.g: read the comments in this video: https://www.youtube.com/watch?v=-PcrLWkxZSk

Decathlon has these _incredibly_ reasonably priced cubes:
https://www.decathlon.pt/bolsa-de-arrumacao-x3-id_8362345.html
![image](https://user-images.githubusercontent.com/194400/45914767-8c40aa80-be41-11e8-9fac-026ccefab1e6.png)

I think it's worth getting them as they save space and can be very tightly packed.

Counter-argument for packing cubes is that they are a "fixed" dimension 
so it makes it difficult to fit more into your bag.
see: https://youtu.be/2Qfrqh-pxPc?t=7m2s
I _totally_ "_reject_" this by saying: you don't need to put _everything_ in Packing Cubes.
For example: I have one for my underwear and one for "smart" shirts. that keeps those two items organised and free from creases (_respectively_). Anything in a packing cube goes into my MLC _first_
I then use the "roll and squeeze" method to pack shirts/tees, shorts/trousers around the cubes.

**Comment by edwardcodes** [comment]
@nelsonic I bought those exactly packing cubes!

**Comment by nelsonic** [comment]
Look forward to hearing your _feedback_ on them when you **`return`** from your travels. 😉
