### ISSUE TITLE
Combination Travel Padlock + Cable

### ISSUE THREAD

**Issue by nelsonic** [edwardcodes/Around-the-World#6]
@edwardcodes I would _highly_ recommend that you consider a **4-digit** combination travel padlock
to _lock_ your bag/backpack when you are _not_ accessing/using it.
_Especially_ if you are planning to travel _alone_ and will be carrying anything of _value_.  
e.g: https://smile.amazon.co.uk/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=4-digit+combination+travel+padlock

https://smile.amazon.co.uk/LWD-Approved-Combination-Retractable-Telescopic/dp/B074S28926
![image](https://user-images.githubusercontent.com/194400/45923678-425cd080-bee4-11e8-8468-7686ddd9c694.png)

2-pack 4-digit lock (_although you probably only need one_) and includes the cable (_see below_)

There are 3-Digit Locks at Decathlon e.g: (_which are "OK"_)
https://www.decathlon.pt/cadeado-com-codigo-30mm-prata-id_8357130.html
![image](https://user-images.githubusercontent.com/194400/45922929-c1480e00-bed0-11e8-91f2-1bc97b845028.png)
however I would _avoid_ getting a 3-digit lock unless you have no other option. 

The difference in possible combinations from 3-digit to 4-digit is 10x.
**3-digit** has **1000 possible combinations** and can be "brute forced" quite quickly by a _novice_ thief.
**4-digit** has ***10k combinations*** which makes it 10x more difficult to _guess_ and at least 3x more time consuming to "crack". (_so you can fairly safely go to the bathroom on a train without worrying about your bag being stolen if you secure it with a steel cable and padlock_)

Note: _Experienced_ lock-pickers ("_crackers_") can crack _any_ lock reasonably quickly:
[![image](https://user-images.githubusercontent.com/194400/45922991-8abec300-bed1-11e8-8186-93b37f1e2da3.png)](https://youtu.be/ABKsUNitXqw)
But having 4-digits instead of 3-digits will _obviously_/_always_ take longer to "crack". 
Whereas a 3-digit combination can _usually_ be "cracked" in under a minute. (_they are kinda pointless_) 

## Steel Cable

Having a steel cable is a _really_ good idea for a solo traveller.
It means you can lock your bag to a physical object like a post or luggage shelf rail:
![image](https://user-images.githubusercontent.com/194400/45923644-99ae7100-bee3-11e8-90a5-e8091a00d47c.png)

### 1 Meter

https://smile.amazon.co.uk/HuntGold-Bicycle-Double-Security-Safety/dp/B071J31RQQ
![image](https://user-images.githubusercontent.com/194400/45923036-919a0580-bed2-11e8-9b8f-4ea4a451fead.png)

![image](https://user-images.githubusercontent.com/194400/45925569-fe7fc080-bf0f-11e8-92a8-e0570f53d0c6.png)

### 2 Meters

https://smile.amazon.co.uk/Aspen-Multi-use-Lightweight-Security-Looped/dp/B06XHJG9MJ
![image](https://user-images.githubusercontent.com/194400/45923037-a1b1e500-bed2-11e8-8bdd-0b7bf8fb763c.png)

The longer one has the potential advantage/bonus of being useful as a "clothes line" to dry laundry:
![image](https://user-images.githubusercontent.com/194400/45923055-2ac91c00-bed3-11e8-862a-f688f3ba16bb.png)
Though _from experience_ (_all_) hostels have laundry facilities which include drying.

### Coiled

https://smile.amazon.co.uk/CloudWhisper-Security-Anti-theft-Reminder-Cable-Straighten/dp/B07D2CH7XB/
![image](https://user-images.githubusercontent.com/194400/45923633-43413280-bee3-11e8-8b3a-7d2636135d65.png)

### High Security --> Kryptonite

https://smile.amazon.co.uk/Kryptonite-Kryptoflex-Foot-Cable-Bike/dp/B000NORUJW
![image](https://user-images.githubusercontent.com/194400/45923067-a7f49100-bed3-11e8-8586-b740404d8b7b.png)

I have/use a Kryptonite cable because I feel that it's the "best".
It has two fairly obvious _disadvantages_:
+ Weight! **322g** (_whereas the 1m x 2mm steel cable above is only **127g**_) 
+ Brand is visible and draws attention. This can be either "deterrent" to thieves or a "eye-catcher" (_signal_) for valuable items being protected ... 

### Cable Lock (_integrated_)

https://smile.amazon.co.uk/Wave-Digit-Cable-Lock-Black/dp/B001R4BPOI
![image](https://user-images.githubusercontent.com/194400/45923106-b3948780-bed4-11e8-92c3-8f830f83544c.png)
Both a "pro" and a "con" of this product is that the cable is _retractable_. 
This means that a thief only has to press the retract button to allow enough "slack" in the cable
so it would be possible to _pry_ the zips appart. 
This is _not_ an issue if you have the **Forclaz 70L** https://github.com/edwardcodes/Around-the-World/issues/4#issuecomment-423731689 because the zip design:
![image](https://user-images.githubusercontent.com/194400/45923121-27cf2b00-bed5-11e8-8bc5-ab16379bbbd8.png)
ensures that the zips are always together when the cable is passed through.

**Comment by nelsonic** [comment]
@edwardcodes you should _consider_ which **`<option>`** you are going to go with _soon_
(_and post a comment with your _decision_ - or any additional research ..._) 
So that the product(s) can be ordered. ⏳

**Comment by edwardcodes** [comment]
https://www.amazon.co.uk/Combination-Lock-BeskooHome-Security-Padlock/dp/B071HGRQ8H/ref=mp_s_a_1_3?ie=UTF8&qid=1537818607&sr=8-3&pi=AC_SX236_SY340_QL65&keywords=locks+4+digits&dpPl=1&dpID=51q6XJlfiaL&ref=plSrch

**Comment by edwardcodes** [comment]
@nelsonic I  really like your options, but what do you think about those two above?

**Comment by edwardcodes** [comment]
In decathlon/sport zone/Leroy merlin etc.. doesn’t have good variety of options with low price

**Comment by edwardcodes** [comment]
https://www.amazon.co.uk/LWD-Approved-Combination-Retractable-Telescopic/dp/B074S28926/ref=mp_s_a_1_31?ie=UTF8&qid=1537819627&sr=8-31&pi=AC_SX236_SY340_QL65&keywords=locks+4+digits+for+backpacks

**Comment by nelsonic** [comment]
Order placed:
![image](https://user-images.githubusercontent.com/194400/46036719-22085e00-c0fe-11e8-9928-d10bb227a0b4.png)
Will be delivered to Tia Carol's house in Carca (_hopefully **before** you leave!_)
If it doesn't arrive "in time" there is a "plan b". 😉

**Comment by nelsonic** [comment]
Amazon Order Update ...
![amazon-order-arriving-4th-october](https://user-images.githubusercontent.com/194400/46244505-b2cd8b00-c3d7-11e8-9c80-f646f25c5d69.png)
No idea why it's taken them so long to _dispatch_ the order ... 😞 
Jokers!
