### ISSUE TITLE
Travel Pillow?

### ISSUE THREAD

**Issue by nelsonic** [edwardcodes/Around-the-World#7]
Given that you are going to try and _maximise_ the distance you can cover on each of your InterRail #2  Travel Days you will _inevitably_ end up sleeping on the Train (_overnight_).
To avoid _destroying_ your neck, I would (_highly_) recommend taking a travel pillow:
![image](https://user-images.githubusercontent.com/194400/45924208-fb75d780-bef1-11e8-8829-bad713bed80e.png)

You could use "spare clothes" as your pillow (_that works if you are "ultra minimalist"_),
but having a _dedicated_ (_purpose built_) pillow is a _much_ better option.

[![image](https://user-images.githubusercontent.com/194400/45924202-d5503780-bef1-11e8-8ef6-0fe452aee9be.png)](https://youtu.be/ZWGIyKVGqmE)
https://youtu.be/ZWGIyKVGqmE

_Decide_ for yourself if you think it's a worthwhile investment and "_effort_" to carry it for the reward of more comfort when sleeping on Transport.
_Then_ do your _own_ research: https://www.amazon.co.uk/Travel-Pillows/b?node=1769608031

I have personally gone though "_phases_" of using and _not_ using Travel/Neck Pillows.
Sometimes I just _forget_ to take it, but _mostly_ I don't travel long enough distances to need one.
You sir, will be travelling _long_ distances/times so sleeping on the transport will be _essential_.
And ensuring that you actually get some _rest_ while sleeping on the train is _mega_ important.
There are some "over night" trains which have sleeping compartments (_do your research!!_) but _most_ trains won't have these luxuries so you will need to [be prepared](https://youtu.be/zPUe7O3ODHQ?t=41s)

**Comment by edwardcodes** [comment]
@nelsonic I’m definitely going to take one! And some ear plugs just in case..

**Comment by nelsonic** [comment]
@edwardcodes I look forward to seeing _your_ research, findings and conclusion/decision 
for _which_ Travel Pillow you are taking. 🤔 

Also, Ear Plugs are a ***must*** not a "just in case". [IMO] 😉 
I would _highly_ recommend that you **open** a **_separate/dedicated_ issue** for Ear Plugs 
and do a _good_ amount of research into which ones you should get/take. 
e.g: find out which Ear Plugs Tim Ferris (_who is good at doing product research_) uses! 🔍 

I _always_ have earplugs with me. (_I store them in the **front pocket** of my "**go bag**"_!)
_However_ I _usually_ end up using a (in-ear) earphones with ["colored noise"](https://github.com/nelsonic/nelsonic.github.io/issues/470) to cancel out ambient noise, and listen to BBC Comedy/Stories in order to fall asleep (_because I'm not [yet] good at clearing my mind!_)
I would be _really_ interested to know which are the "best" earplugs and _why_ because I would _love_ to "wean" myself off using "colored noise", "classical music" or BBC radio to concentrate and fall asleep respectively. Please _share_ your research/findings! ❤️ ✅

**Comment by edwardcodes** [comment]
@nelsonic This travel pillow looks really good/comfy but I’m going to try it out on the store. 
https://www.decathlon.pt/almofada-viagem-confort-preto-id_8361862.html

**Comment by nelsonic** [comment]
@edwardcodes I've never been "convinced" by _inflatable_ travel pillows.
They offer _support_ but not _comfort_. 
https://www.decathlon.pt/almofada-viagem-confort-preto-id_8361862.html
![image](https://user-images.githubusercontent.com/194400/45985615-f8e4c080-c05e-11e8-9ad0-2a65b2af55ea.png)

As you say, you're going to _test_ it in the store ... I'm keen to read your feedback.

**Comment by edwardcodes** [comment]
@nelsonic I didn’t test it in the store because they were just terrible 😅
Instead I went to Natura and bought a really comfortable neck pillow:
https://loja.imaginarium.com.br/almofada-de-pescoco-mapa/p (It’s very similar to this one)

**Comment by nelsonic** [comment]
Nice. I look forward to seeing it. 👍
